// Export all user API functions and types
export {
  loginUser,
  logoutUser,
  createUser,
  updateUser,
  updateUserStatus,
  createDepartment,
  updateDepartment,
  deleteDepartment,
  deleteUser,
  getUsers,
  getDepartments,
  getUserProfile,
  updateUserProfile,
  getRidesTrend,
  getRidersPerformance,
  getActiveRides,
  updateLocation,
  generateReport,
  getReportsMeta,
  getReportsList,
  downloadReport,
  storeAuthToken,
  getAuthToken,
  removeAuthToken,
  isAuthenticated,
  handleApiError,
  type LoginRequest,
  type LoginResponse,
  type CreateUserRequest,
  type CreateUserResponse,
  type UpdateUserRequest,
  type UpdateUserResponse,
  type UpdateUserStatusRequest,
  type UpdateUserStatusResponse,
  type CreateDepartmentRequest,
  type CreateDepartmentResponse,
  type UpdateDepartmentRequest,
  type UpdateDepartmentResponse,
  type DeleteDepartmentResponse,
  type ApiError,
  type User,
  type GetUsersResponse,
  type Department,
  type GetDepartmentsResponse,
  type RidesTrendDataPoint,
  type RidesTrendResponse,
  type RiderPerformanceDataPoint,
  type RidersPerformanceResponse,
  type GetUserProfileResponse,
  type UpdateUserProfileRequest,
  type GenerateReportRequest,
  type GenerateReportResponse,
} from './api';
